# -*- coding: utf-8 -*-
"""stat 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fnW1R9dGYuBo8PGGdzR5lLm45g6hzmCs

1. What is the difference between descriptive statistics and inferential
statistics? Explain with examples

Descriptive statistics

Purpose: To summarize and organize data to make it easier to understand.
Focus: Describes the characteristics of the specific group or dataset being analyzed, without making generalizations to a larger population.
Methods: Uses measures of central tendency (like mean, median, mode) and measures of dispersion (like range, standard deviation, variance). Visualization techniques like graphs, charts, and tables are also used.
Example: A teacher calculates the average test score for their class of 30 students to describe that class's performance. The average score of 82.5% is a descriptive statistic for that specific group


Inferential statistics


Purpose: To use data from a sample to make inferences, predictions, or generalizations about a larger population.
Focus: Goes beyond the immediate data to draw conclusions about a population based on a sample.
Methods: Uses probability to make predictions and tests of significance, such as t-tests, ANOVA, and chi-square tests.
Example: A survey of 1,000 registered voters (the sample) is used to predict the voting intention of all registered voters in the country (the population). The result might be a statement like, "Candidate A has an estimated 52% support, with a 3% margin of error"

2.What is sampling in statistics? Explain the differences between random
and stratified sampling

Sampling is the process of selecting a subset of a population to use in a study, and the main difference between random and stratified sampling is how the subset is chosen. Random sampling selects individuals from the entire population without any consideration for subgroups, while stratified sampling first divides the population into smaller groups (strata) based on shared characteristics and then takes a random sample from each group. This ensures that every subgroup is represented in a stratified sample, unlike a simple random sample where some groups might be missed.


Random sampling


Definition: A method where every member of the population has an equal chance of being selected for the sample.
Process: A single random selection is made from the entire population.
Goal: To obtain a representative sample of the whole population, treating all individuals as equal.
Example: If you are surveying students in a large university, a simple random sample might be to put all 30,000 student ID numbers into a hat and draw 1,000 of them


Stratified sampling

Definition: A method that divides the population into distinct subgroups (strata) before sampling.
Process: The population is first divided into strata (e.g., by age, gender, or income), and then a random sample is drawn from each of these subgroups.
Goal: To ensure that all subgroups are adequately represented in the sample, which can provide more precise and reliable results, especially when comparing differences between groups.
Example: To survey students in the same university, you could first divide the students into four strata based on their college (Arts, Science, Engineering, and Business). You would then randomly select a proportionate number of students from each of these four groups to form your sample.

3.Define mean, median, and mode. Explain why these measures of central
tendency are important.

Mean is the average, median is the middle value, and mode is the most frequent value in a dataset. These measures are important because they help summarize a large dataset with a single number, allowing for easier understanding of a data set's center and typical value. They provide insights into the distribution, help in comparisons, and support data-driven decision-making.


Definitions

Mean: The arithmetic average of a dataset, calculated by adding all values and dividing by the number of values. For example, the mean of {\(2,3,4\)} is \((2+3+4)\div 3=3\).

Median: The middle value in a dataset that has been ordered from least to greatest. If there is an even number of values, the median is the average of the two middle values. For example, the median of {\(2,3,4\)} is \(3\). The median of {\(2,3,4,5\)} is the average of \(3\) and \(4\), which is \(3.5\).

Mode: The value that appears most often in a dataset. A dataset can have one mode, multiple modes (bimodal or multimodal), or no mode at all. For example, the mode of {\(2,2,3,4\)} is \(2\)

Importance
Summarize data: They condense a large set of numbers into a single, representative value, making data sets much easier to understand at a glance.
Provide different insights: Each measure highlights a different aspect of the data's center:
The mean gives the average and is affected by all values, including outliers.
The median is the middle point and is less affected by extreme outliers.
The mode shows the most common value, which is useful for identifying popularity or frequency.
Aid in decision-making: By providing a quick summary, these measures help in making comparisons and drawing conclusions in fields like economics, public health, and science.
Understand data distribution: Comparing the mean, median, and mode can help you understand the shape of the data's distribution. For example, if the mean is significantly higher than the median, it suggests the presence of high-value outliers.

4. Explain skewness and kurtosis. What does a positive skew imply about the
data?

Skewness measures a distribution's asymmetry, while kurtosis measures its peakedness or "tailedness". A positively skewed distribution has a tail that is longer on the right, meaning most of the data is concentrated on the left, and the mean is greater than the median

Skewness and kurtosis
Skewness: Indicates the degree of asymmetry in a data distribution.
Zero skew: The distribution is symmetrical (like a normal distribution).
Positive skew: The right tail is longer, and the distribution is pulled to the right.
Negative skew: The left tail is longer, and the distribution is pulled to the left.

Kurtosis: Measures how heavy or light the tails of a distribution are compared to a normal distribution.
Mesokurtic: Kurtosis value is 3, similar to a normal distribution.
Leptokurtic: Positive kurtosis (greater than 3), indicating heavier tails and a sharper peak.
Platykurtic: Negative kurtosis (less than 3), indicating lighter tails and a flatter peak.

Positive skew implication A positive skew implies that the data is not symmetrical and is pulled to the right. The mean is greater than the median, which is greater than the mode (\(mean>median>mode\)).This is because the long tail on the right side is influenced by a few high-value outliers, which pulls the mean higher than the median.Most of the data points are clustered on the left side of the distribution

5.Implement a Python program to compute the mean, median, and mode of
a given list of numbers.
numbers = [12, 15, 12, 18, 19, 12, 20, 22, 19, 19, 24, 24, 24, 26, 28]
"""

import statistics
from collections import Counter

def calculate_statistics(numbers):
    """
    Calculates the mean, median, and mode of a list of numbers.

    Args:
        numbers: A list of numerical values.

    Returns:
        A tuple containing the mean, median, and a list of modes.
    """
    if not numbers:
        return None, None, []

    # Calculate Mean
    mean = sum(numbers) / len(numbers)

    # Calculate Median
    median = statistics.median(numbers)

    # Calculate Mode(s)
    # Using collections.Counter to count occurrences of each number
    counts = Counter(numbers)
    max_count = max(counts.values())
    modes = [key for key, value in counts.items() if value == max_count]

    return mean, median, modes

# Given list of numbers
numbers = [12, 15, 12, 18, 19, 12, 20, 22, 19, 19, 24, 24, 24, 26, 28]

# Calculate and print the statistics
mean_value, median_value, mode_values = calculate_statistics(numbers)

print(f"Given numbers: {numbers}")
print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Mode(s): {mode_values}")

"""6.Compute the covariance and correlation coefficient between the following
two datasets provided as lists in Python:
list_x = [10, 20, 30, 40, 50]
list_y = [15, 25, 35, 45, 60]
"""

import numpy as np

list_x = [10, 20, 30, 40, 50]
list_y = [15, 25, 35, 45, 60]

# Convert lists to NumPy arrays for easier calculation
array_x = np.array(list_x)
array_y = np.array(list_y)

# Calculate covariance
# np.cov returns a covariance matrix. For two arrays, the covariance between them is the off-diagonal element.
covariance_matrix = np.cov(array_x, array_y)
covariance = covariance_matrix[0, 1] # or covariance_matrix[1, 0]

# Calculate correlation coefficient
correlation_coefficient = np.corrcoef(array_x, array_y)[0, 1]

"""7.: Write a Python script to draw a boxplot for the following numeric list and
identify its outliers. Explain the result:
data = [12, 14, 14, 15, 18, 19, 19, 21, 22, 22, 23, 23, 24, 26, 29, 35]
"""

import matplotlib.pyplot as plt
import numpy as np

data = [12, 14, 14, 15, 18, 19, 19, 21, 22, 22, 23, 23, 24, 26, 29, 35]

# Create a boxplot
plt.figure(figsize=(8, 6))
plt.boxplot(data)
plt.title('Boxplot of Data')
plt.ylabel('Values')
plt.grid(True)
plt.show()

# Calculate quartiles and IQR to identify outliers
Q1 = np.percentile(data, 25)
Q3 = np.percentile(data, 75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = [x for x in data if x < lower_bound or x > upper_bound]

print(f"First Quartile (Q1): {Q1}")
print(f"Third Quartile (Q3): {Q3}")
print(f"Interquartile Range (IQR): {IQR}")
print(f"Lower Bound for Outliers: {lower_bound}")
print(f"Upper Bound for Outliers: {upper_bound}")
print(f"Identified Outliers: {outliers}")

"""8.: You are working as a data analyst in an e-commerce company. The
marketing team wants to know if there is a relationship between advertising spend and
daily sales.
● Explain how you would use covariance and correlation to explore this
relationship.
● Write Python code to compute the correlation between the two lists:
advertising_spend = [200, 250, 300, 400, 500]
daily_sales = [2200, 2450, 2750, 3200, 4000]
"""

import math

# Data provided
advertising_spend = [200, 250, 300, 400, 500]
daily_sales = [2200, 2450, 2750, 3200, 4000]

def calculate_correlation(x, y):
    """
    Computes the Pearson correlation coefficient for two lists.
    Args:
        x (list): The list of advertising spend data.
        y (list): The list of daily sales data.
    Returns:
        float: The correlation coefficient.
    """
    n = len(x)

    # Calculate summations
    sum_x = sum(x)
    sum_y = sum(y)
    sum_xy = sum(i * j for i, j in zip(x, y))
    sum_x2 = sum(i ** 2 for i in x)
    sum_y2 = sum(j ** 2 for j in y)

    # Calculate the numerator and denominator
    numerator = n * sum_xy - sum_x * sum_y
    denominator = math.sqrt((n * sum_x2 - sum_x ** 2) * (n * sum_y2 - sum_y ** 2))

    # Handle division by zero for cases with no variance
    if denominator == 0:
        return 0

    return numerator / denominator

# Compute and print the correlation
correlation = calculate_correlation(advertising_spend, daily_sales)
print(f"The correlation between advertising spend and daily sales is: {correlation:.4f}")

"""9.Your team has collected customer satisfaction survey data on a scale of
1-10 and wants to understand its distribution before launching a new product.
● Explain which summary statistics and visualizations (e.g. mean, standard
deviation, histogram) you’d use.
● Write Python code to create a histogram using Matplotlib for the survey data:
survey_scores = [7, 8, 5, 9, 6, 7, 8, 9, 10, 4, 7, 6, 9, 8, 7]

"""

import matplotlib.pyplot as plt

# The survey data
survey_scores = [7, 8, 5, 9, 6, 7, 8, 9, 10, 4, 7, 6, 9, 8, 7]

# Create the histogram
# The `bins` parameter is set to a range of values (1 to 10) to clearly
# show the frequency for each integer score.
plt.hist(survey_scores, bins=range(4, 12), edgecolor='black', rwidth=0.9)

# Add title and labels
plt.title('Distribution of Customer Satisfaction Scores')
plt.xlabel('Survey Score (1-10)')
plt.ylabel('Frequency')

# Set x-axis ticks to match the score scale
plt.xticks(range(4, 11))

# Display the plot
plt.show()